M48
; DRILL file {KiCad (6.0.2)} date Wed Mar 30 20:09:58 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-30T20:09:58+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X4.0103Y-4.9862
X4.0103Y-5.2138
T2
X4.5809Y-4.867
X4.6991Y-4.867
T0
M30
